name: Hello World

on: [workflow_dispatch]

jobs:
  hello-world:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line PowerShell script
      run: |
        if (!(Test-Path "./test.txt")) { New-Item -ItemType File -Name "./text.txt" }
        Add-Content "./test.txt" "asd qwe"
        git config --global user.name "Glorp"
        git config --global user.email "glorp@users.noreply.github.com"
        git add -A
        git commit -m "added stuff"
        git push
