name: Hello World

on: [workflow_dispatch]

jobs:
  hello-world:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master
    - name: Run PowerShell Hello World script
      run: Write-Output 'Hello World!'
    - name: Run a multi-line PowerShell script
      run: |
        if (!(Test-Path "./test.txt")) { New-Item -ItemType File -Name "./text.txt" }
        Add-Content "./test.txt" "asd qwe"
        git add -A
        git commit
        git push
